### ISSUE TITLE
FEATURE reverse ssh for getting decrypt key

### ISSUE THREAD

**Issue by MyraBaba** [89luca89/pakkero#8]
Hi,

is it possible to use ssh/reverse ssh to get decryting key ?

**Comment by MyraBaba** [comment]
we are decrypting something ,ie function or data etc right. And we are keeping this in the program. 

Imagine a program: launching, and revers ssh'ed to a license server , license server ssh'ed back or somehow enter the required.

**Comment by 89luca89** [comment]
It's out of scope on what pakkero aims to be, but you're free to fork and modify and develop your idea :+1:
